Taobao: # dataset_id
    data_root: ../../../data/
    data_format: h5
    train_data: ../../../data/Taobao/train.csv
    valid_data: ../../../data/Taobao/valid.csv
    test_data: ../../../data/Taobao/test.csv
    min_categr_count: 1
    feature_cols:
        - {name: ["userid","adgroup_id","pid","cate_id","campaign_id","customer","brand","cms_segid",
                  "cms_group_id","final_gender_code","age_level","pvalue_level","shopping_level","occupation"], 
                  active: True, dtype: str, type: categorical}
    label_col: {name: clk, dtype: float}